title: !secret home_name
resources:
  - url: /local/mini-media-player-bundle.js?v=1.6.0
    type: module
views:
  - !include ui/home.yaml
  - !include ui/switches.yaml
  - !include ui/media.yaml
  - !include ui/status.yaml
background: var(--background-image)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: '{{ hours24 }}:{{ minutesLZ }}'
