alias: 'In the morning during the week, turn on the office'
trigger:
  - platform: sun
    event: sunrise
    offset: '-01:00:00'
  - platform: state
    entity_id: device_tracker.olivers_iphone_x
    to: 'home'
condition:
  - condition: state
    entity_id: device_tracker.olivers_iphone_x
    state: 'home'
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: time
    after: '06:00:00'
    before: '11:00:00'
action:
  service: homeassistant.turn_on
  entity_id: group.office
