alias: 'In the evening, if people are home, turn on the living room'
trigger:
  - platform: sun
    event: sunset
    offset: '-01:00:00'
  - platform: state
    entity_id: device_tracker.olivers_iphone_x
    to: 'home'
condition:
  - condition: state
    entity_id: device_tracker.olivers_iphone_x
    state: 'home'
  - condition: time
    after: '16:00:00'
    before: '23:00:00'
action:
  service: homeassistant.turn_on
  entity_id: group.living_room
