name: "Lint"
on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Lint YAML
        run: make lint
      - name: Check Configuration
        run:
          - cp secrets.example.yaml secrets.yaml 
          - make check
