name: Lint YAML
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install YAMLLint
        run: python -m pip install --upgrade pip setuptools wheel yamllint
      - name: Run YAMLLint
        run: yamllint -c .yamllint.yaml .
